Repository 2025-cs-study/short-octopus-leg, pull requests merged in 2025-08, with the labels that each got.

#6 [민주] jbd : 성능을 좌우하는 DB 설계와 쿼리
  02_index.md
Labels: chapter03, jbd

#10 [서희] jbd : 외부 연동이 문제일 때 살펴봐야 할 것들
  03_external_API_integration.md
  img/03_1.png
  img/03_2.png
Labels: chapter04

#3 [서희] jbd : 느려진 서비스, 어디부터 봐야 할까
  01_DB_connection_pool.md
Labels: chapter02, jbd

#12 [서희] jbd : 비동기 연동, 언제 어떻게 써야 할까
  04_async_integration.md
  img/04_1.png
  img/04_2.png
Labels: chapter05, jbd
